"use client";

import { useState, useEffect } from "react";
import { Plus, Trash2, X, Image as ImageIcon, Loader2 } from "lucide-react";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "@/components/ui/sheet";

import { BaseCategories, BaseCategoriesIds } from "@/data/categories";
import { BaseCustomizationsObj } from "@/data/customizations";
import { DBProduct } from "@/types/product";
import { uploadImageToS3, generateImageKey } from "@/lib/aws-s3";
import Image from "next/image";
import { addProduct } from "@/lib/products";
import { getNewProductDocId } from "@/lib/firebase";
import { compressImage } from "@/lib/images";
import { DBCustomization } from "@/types/customization";
import { getTimestamp } from "@/utils/misc";
import { getCurrencySymbol } from "@/utils/price";

// Helper function to clean object of undefined/empty values
const cleanObject = (obj: unknown): unknown => {
  if (Array.isArray(obj)) {
    return obj
      .map(cleanObject)
      .filter(
        (item) =>
          item !== null && item !== undefined && item !== "" && item !== 0
      );
  }

  if (obj !== null && typeof obj === "object") {
    const cleaned: Record<string, unknown> = {};
    Object.entries(obj).forEach(([key, value]) => {
      const cleanedValue = cleanObject(value);
      if (
        cleanedValue !== null &&
        cleanedValue !== undefined &&
        cleanedValue !== "" &&
        cleanedValue !== 0
      ) {
        if (Array.isArray(cleanedValue)) {
          cleaned[key] = cleanedValue;
        } else if (typeof cleanedValue === "object") {
          cleaned[key] = cleanedValue;
        } else {
          cleaned[key] = cleanedValue;
        }
      }
    });
    return Object.keys(cleaned).length > 0 ? cleaned : null;
  }

  return obj;
};

// Type for image state to handle files and preview URLs
interface ImageState {
  file: File | null;
  preview: string;
}

const defaultProductData: DBProduct = {
  id: "", // This will be generated by the server
  name: "",
  description: "",
  dimensions: "",
  weight: 0,
  images: [],
  slug: "",
  price: 0,
  categoryId: "keychains" as BaseCategoriesIds,
  customizationOptions: [] as DBCustomization[],
  available: true,
  isBestSeller: false,
  createdAt: getTimestamp(),
};

interface ProductSheetProps {
  trigger?: React.ReactNode;
  onProductSaved?: () => void;
}

export function ProductSheet({ trigger, onProductSaved }: ProductSheetProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [isUploading, setIsUploading] = useState(false);
  const [productData, setProductData] = useState(defaultProductData);

  // State for handling file uploads and previews
  const [imageStates, setImageStates] = useState<ImageState[]>([
    { file: null, preview: "" },
  ]);

  // Reset form when sheet closes
  useEffect(() => {
    if (!isOpen) {
      setProductData(defaultProductData);
      setImageStates([{ file: null, preview: "" }]);
    }
  }, [isOpen]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsUploading(true);

    try {
      const finalImageUrls: string[] = [];

      // Generate new product ID
      const productId = await getNewProductDocId();
      console.log("New Product ID:", productId);

      // Handle image uploads
      for (const imageState of imageStates) {
        if (imageState.file) {
          const imageKey = generateImageKey(imageState.file.name, productId);
          const compressedImage = await compressImage(imageState.file);
          const uploadedUrl = await uploadImageToS3(compressedImage, imageKey);
          finalImageUrls.push(uploadedUrl);
        }
      }

      // Create SEO-friendly slug by removing filler words
      const stopWords = [
        "and",
        "for",
        "the",
        "a",
        "an",
        "or",
        "but",
        "in",
        "on",
        "at",
        "to",
        "with",
        "by",
        "of",
        "is",
        "are",
        "was",
        "were",
        "be",
        "been",
        "have",
        "has",
        "had",
        "do",
        "does",
        "did",
        "will",
        "would",
        "could",
        "should",
        "may",
        "might",
        "can",
        "this",
        "that",
        "these",
        "those",
      ];

      const slug =
        productData.name
          .toLowerCase()
          .trim()
          .split(/\s+/) // Split by one or more whitespace characters
          .filter((word) => word.length > 0 && !stopWords.includes(word)) // Remove empty strings and stop words
          .join("-") +
        "-" +
        productId;

      // Update product data with final image URLs
      const finalProductData: DBProduct = {
        ...productData,
        slug,
        images: finalImageUrls,
        createdAt: getTimestamp(),
      };

      const cleanedData: DBProduct = cleanObject(finalProductData) as DBProduct;
      console.log("Clean Product data:", cleanedData);

      // eslint-disable-next-line @typescript-eslint/no-unused-vars
      const { id: _, ...cleanedDataWithoutId } = cleanedData;

      // Add new product
      await addProduct(productId, cleanedDataWithoutId);

      // Trigger callback
      onProductSaved?.();

      // Reset form and close
      setProductData(defaultProductData);
      setImageStates([{ file: null, preview: "" }]);
      setIsOpen(false);
    } catch (error) {
      console.error("Error saving product:", error);
      alert("Error saving product. Please try again.");
    } finally {
      setIsUploading(false);
    }
  };

  const addCustomization = () => {
    setProductData((prev) => ({
      ...prev,
      customizationOptions: [
        ...prev.customizationOptions,
        {
          customizationRefId: "",
        },
      ],
    }));
  };

  const addImage = () => {
    setImageStates((prev) => [...prev, { file: null, preview: "" }]);
  };

  const removeImage = (index: number) => {
    if (imageStates.length > 1) {
      setImageStates((prev) => prev.filter((_, i) => i !== index));
    }
  };

  const removeCustomization = (index: number) => {
    setProductData((prev) => ({
      ...prev,
      customizationOptions: prev.customizationOptions.filter(
        (_, i) => i !== index
      ),
    }));
  };

  const handleImageChange = (index: number, file: File | null) => {
    if (file) {
      const reader = new FileReader();
      reader.onload = (e) => {
        setImageStates((prev) =>
          prev.map((state, i) =>
            i === index
              ? {
                  file,
                  preview: e.target?.result as string,
                }
              : state
          )
        );
      };
      reader.readAsDataURL(file);
    } else {
      setImageStates((prev) =>
        prev.map((state, i) =>
          i === index ? { file: null, preview: "" } : state
        )
      );
    }
  };

  const loadBaseCustomization = (customizationRefId: string, index: number) => {
    if (customizationRefId && BaseCustomizationsObj[customizationRefId]) {
      setProductData((prev) => ({
        ...prev,
        customizationOptions: prev.customizationOptions.map((option, i) =>
          i === index ? { customizationRefId } : option
        ),
      }));
    }
  };

  const sheetContent = (
    <SheetContent className="w-[700px] sm:max-w-none overflow-y-auto p-8">
      <SheetHeader className="pb-6">
        <SheetTitle className="text-2xl">Add New Product</SheetTitle>
        <SheetDescription className="text-base">
          Create a new product with customization options
        </SheetDescription>
      </SheetHeader>

      <form onSubmit={handleSubmit} className="space-y-8">
        {/* Basic Product Info */}
        <div className="space-y-6 p-6 border rounded-lg">
          <h3 className="text-lg font-semibold">Basic Information</h3>

          <div className="space-y-2">
            <label className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
              Category
            </label>
            <Select
              value={productData.categoryId}
              onValueChange={(value) =>
                setProductData((prev) => ({
                  ...prev,
                  categoryId: value as BaseCategoriesIds,
                }))
              }
            >
              <SelectTrigger>
                <SelectValue placeholder="Select a category" />
              </SelectTrigger>
              <SelectContent>
                {BaseCategories.map((category) => (
                  <SelectItem key={category.id} value={category.id}>
                    {category.name}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <div className="space-y-2">
            <label className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
              Product Name
            </label>
            <Input
              placeholder="Enter product name"
              value={productData.name}
              onChange={(e) =>
                setProductData((prev) => ({ ...prev, name: e.target.value }))
              }
              required
            />
          </div>

          <div className="space-y-2">
            <label className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
              Description
            </label>
            <Textarea
              placeholder="Enter product description"
              className="min-h-24"
              value={productData.description || ""}
              onChange={(e) =>
                setProductData((prev) => ({
                  ...prev,
                  description: e.target.value,
                }))
              }
            />
          </div>

          <div className="space-y-2">
            <label className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
              Dimensions
            </label>
            <Input
              placeholder="e.g., 5cm x 3cm x 1cm"
              value={productData.dimensions}
              onChange={(e) =>
                setProductData((prev) => ({
                  ...prev,
                  dimensions: e.target.value,
                }))
              }
              required
            />
          </div>

          <div className="space-y-2">
            <label className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
              Weight
            </label>
            <Input
              placeholder="e.g., 5"
              value={productData.weight?.toString() || ""}
              onChange={(e) =>
                setProductData((prev) => ({
                  ...prev,
                  weight: parseFloat(e.target.value) || 0,
                }))
              }
              required
            />
          </div>

          <div className="space-y-2">
            <label className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
              Price ({getCurrencySymbol()})
            </label>
            <Input
              type="number"
              placeholder="0.00"
              value={productData.price || 0}
              onChange={(e) =>
                setProductData((prev) => ({
                  ...prev,
                  price: parseFloat(e.target.value) || 0,
                }))
              }
              required
            />
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <label className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
                Available
              </label>
              <Select
                value={productData.available.toString()}
                onValueChange={(value) =>
                  setProductData((prev) => ({
                    ...prev,
                    available: value === "true",
                  }))
                }
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="true">Yes</SelectItem>
                  <SelectItem value="false">No</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <label className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
                Best Seller
              </label>
              <Select
                value={productData.isBestSeller.toString()}
                onValueChange={(value) =>
                  setProductData((prev) => ({
                    ...prev,
                    isBestSeller: value === "true",
                  }))
                }
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="true">Yes</SelectItem>
                  <SelectItem value="false">No</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>
        </div>

        {/* Product Images */}
        <div className="space-y-6 p-6 border rounded-lg">
          <div className="flex items-center justify-between">
            <h3 className="text-lg font-semibold">Product Images</h3>
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={addImage}
            >
              <ImageIcon className="w-4 h-4 mr-2" />
              Add Image
            </Button>
          </div>

          <div className="space-y-4">
            {imageStates.map((imageState, index) => (
              <div key={index} className="border rounded-lg p-4">
                <div className="flex gap-4">
                  {/* Image Preview */}
                  <div className="flex-shrink-0">
                    {imageState.preview ? (
                      <div className="relative">
                        <Image
                          src={imageState.preview}
                          alt={`Preview ${index + 1}`}
                          width={80}
                          height={80}
                          className="w-20 h-20 object-cover rounded-md border"
                        />
                        <Button
                          type="button"
                          variant="outline"
                          size="icon"
                          className="absolute -top-2 -right-2 h-6 w-6"
                          onClick={() => handleImageChange(index, null)}
                        >
                          <X className="w-3 h-3" />
                        </Button>
                      </div>
                    ) : (
                      <div className="w-20 h-20 border-2 border-dashed border-border rounded-md flex items-center justify-center">
                        <ImageIcon className="w-8 h-8 text-muted-foreground" />
                      </div>
                    )}
                  </div>

                  {/* File Input */}
                  <div className="flex-1 space-y-2">
                    <label className="text-sm font-medium">
                      Image {index + 1}
                    </label>
                    <div className="flex gap-2">
                      <Input
                        type="file"
                        accept="image/*"
                        onChange={(e) => {
                          const file = e.target.files?.[0] || null;
                          handleImageChange(index, file);
                        }}
                        className="flex-1"
                      />
                      {imageStates.length > 1 && (
                        <Button
                          type="button"
                          variant="outline"
                          size="icon"
                          onClick={() => removeImage(index)}
                        >
                          <Trash2 className="w-4 h-4" />
                        </Button>
                      )}
                    </div>
                    {imageState.file && (
                      <p className="text-xs text-muted-foreground">
                        {imageState.file.name} (
                        {Math.round(imageState.file.size / 1024)} KB)
                      </p>
                    )}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Customization Options */}
        <div className="space-y-6 p-6 border rounded-lg">
          <div className="flex items-center justify-between">
            <h3 className="text-lg font-semibold">Customization Options</h3>
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={addCustomization}
            >
              <Plus className="w-4 h-4 mr-2" />
              Add Customization
            </Button>
          </div>

          <div className="space-y-6">
            {productData.customizationOptions.length > 0 &&
              productData.customizationOptions.map((option, index) => (
                <div
                  key={index}
                  className="border rounded-lg p-6 space-y-6 bg-muted/20"
                >
                  <div className="flex items-center justify-between">
                    <h4 className="font-medium text-lg">
                      Customization Option {index + 1}
                      {option.customizationRefId &&
                        BaseCustomizationsObj[option.customizationRefId] && (
                          <span className="text-sm font-normal text-muted-foreground ml-2">
                            (Based on:{" "}
                            {
                              BaseCustomizationsObj[option.customizationRefId]
                                .label
                            }
                            )
                          </span>
                        )}
                    </h4>
                    <Button
                      type="button"
                      variant="outline"
                      size="icon"
                      onClick={() => removeCustomization(index)}
                    >
                      <X className="w-4 h-4" />
                    </Button>
                  </div>

                  {/* Base Customization Selector */}
                  <div className="p-4 bg-background rounded-md border">
                    <div className="flex items-center justify-between mb-3">
                      <label className="text-sm font-medium">
                        Load from Base Customizations
                      </label>
                    </div>
                    <Select
                      value={option.customizationRefId || ""}
                      onValueChange={(value) =>
                        loadBaseCustomization(value, index)
                      }
                    >
                      <SelectTrigger>
                        <SelectValue placeholder="Select a base customization to load" />
                      </SelectTrigger>
                      <SelectContent>
                        {Object.entries(BaseCustomizationsObj)
                          .filter(
                            ([, customization]) =>
                              customization.categoryId ===
                              productData.categoryId
                          )
                          .map(([id, customization]) => (
                            <SelectItem key={id} value={id}>
                              {customization.label} ({customization.type})
                            </SelectItem>
                          ))}
                      </SelectContent>
                    </Select>
                    {option.customizationRefId &&
                      BaseCustomizationsObj[option.customizationRefId] && (
                        <div className="mt-2 text-xs text-muted-foreground">
                          Base values:{" "}
                          {
                            BaseCustomizationsObj[option.customizationRefId]
                              .label
                          }{" "}
                          •
                          {
                            BaseCustomizationsObj[option.customizationRefId]
                              .type
                          }{" "}
                          • {getCurrencySymbol()}
                          {
                            BaseCustomizationsObj[option.customizationRefId]
                              .priceAdd
                          }{" "}
                          •
                          {BaseCustomizationsObj[option.customizationRefId]
                            .required
                            ? "Required"
                            : "Optional"}
                        </div>
                      )}
                  </div>
                </div>
              ))}
          </div>
        </div>

        <div className="flex justify-end space-x-4 pt-6">
          <Button
            type="button"
            variant="outline"
            onClick={() => setIsOpen(false)}
            disabled={isUploading}
          >
            Cancel
          </Button>
          <Button type="submit" disabled={isUploading}>
            {isUploading ? (
              <>
                <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                Uploading...
              </>
            ) : (
              <>
                <Plus className="w-4 h-4 mr-2" />
                Add Product
              </>
            )}
          </Button>
        </div>
      </form>
    </SheetContent>
  );

  return (
    <Sheet open={isOpen} onOpenChange={setIsOpen}>
      {trigger && <SheetTrigger asChild>{trigger}</SheetTrigger>}
      {sheetContent}
    </Sheet>
  );
}

// Convenience component for adding products
export function AddProductSheet({
  onProductSaved,
}: {
  onProductSaved?: () => void;
}) {
  return (
    <ProductSheet
      trigger={
        <Button>
          <Plus className="w-4 h-4 mr-1" />
          Add Product
        </Button>
      }
      onProductSaved={onProductSaved}
    />
  );
}
